version: '3'

services:

  nginx:
    build: build/nginx
    container_name: ${CLIENT}.nginx.${ENV}
    hostname: nginx
    volumes:
      - ../volume/nginx/etc.nginx.sites-enabled:/etc/nginx/sites-enabled
      - ../volume/www:/home/www
    ports:
      - "80:80" # http
    depends_on: # sert à attendre que les services soient prêts avant de démarrer
      - php
      - react
    restart: always

  mysql:
    build: build/mysql
    container_name: ${CLIENT}.mysql.${ENV}
    hostname: mysql
    env_file: env/mysql.env
    volumes:
      - ../volume/mysql/var.lib.mysql:/var/lib/mysql
    restart: always

  api:
    build: build/php
    container_name: ${CLIENT}.api.${ENV}
    hostname: php
    volumes:
      - ../volume/www:/home/www
    restart: always

  app:
    build: build/react
    container_name: ${CLIENT}.app.${ENV}
    hostname: react
    volumes:
      - ../volume/www:/home/www
    restart: always